/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Transaction {
  'id' : string,
  'transactionType' : TransactionType,
  'description' : string,
  'pixKey' : string,
  'timestamp' : bigint,
  'balanceAfter' : bigint,
  'amount' : bigint,
}
export type TransactionType = { 'receivedPix' : null } |
  { 'cofrinhoDeposit' : null } |
  { 'cofrinhoWithdrawal' : null } |
  { 'sentPix' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletState {
  'cofrinhoBalance' : bigint,
  'balance' : bigint,
  'transactions' : Array<Transaction>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'depositCofrinho' : ActorMethod<
    [bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletState' : ActorMethod<[], WalletState>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendPix' : ActorMethod<
    [string, bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'simulateReceivePix' : ActorMethod<[bigint, string], bigint>,
  'withdrawCofrinho' : ActorMethod<
    [bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];