/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TransactionType = IDL.Variant({
  'receivedPix' : IDL.Null,
  'cofrinhoDeposit' : IDL.Null,
  'cofrinhoWithdrawal' : IDL.Null,
  'sentPix' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'description' : IDL.Text,
  'pixKey' : IDL.Text,
  'timestamp' : IDL.Int,
  'balanceAfter' : IDL.Int,
  'amount' : IDL.Int,
});
export const WalletState = IDL.Record({
  'cofrinhoBalance' : IDL.Int,
  'balance' : IDL.Int,
  'transactions' : IDL.Vec(Transaction),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'depositCofrinho' : IDL.Func(
      [IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletState' : IDL.Func([], [WalletState], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendPix' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
      [],
    ),
  'simulateReceivePix' : IDL.Func([IDL.Int, IDL.Text], [IDL.Int], []),
  'withdrawCofrinho' : IDL.Func(
      [IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TransactionType = IDL.Variant({
    'receivedPix' : IDL.Null,
    'cofrinhoDeposit' : IDL.Null,
    'cofrinhoWithdrawal' : IDL.Null,
    'sentPix' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'description' : IDL.Text,
    'pixKey' : IDL.Text,
    'timestamp' : IDL.Int,
    'balanceAfter' : IDL.Int,
    'amount' : IDL.Int,
  });
  const WalletState = IDL.Record({
    'cofrinhoBalance' : IDL.Int,
    'balance' : IDL.Int,
    'transactions' : IDL.Vec(Transaction),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'depositCofrinho' : IDL.Func(
        [IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletState' : IDL.Func([], [WalletState], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendPix' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
        [],
      ),
    'simulateReceivePix' : IDL.Func([IDL.Int, IDL.Text], [IDL.Int], []),
    'withdrawCofrinho' : IDL.Func(
        [IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };